apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
      alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
      alb.ingress.kubernetes.io/subnets: {{ .Values.ingress.subnets }}
      alb.ingress.kubernetes.io/security-groups: {{ .Values.ingress.securityGroup }}
      alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateArn }}
      alb.ingress.kubernetes.io/healthcheck-interval-seconds: '10'
      alb.ingress.kubernetes.io/healthcheck-path: '/healthz'
      alb.ingress.kubernetes.io/healthcheck-protocol: 'HTTP'
      alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '6'
      alb.ingress.kubernetes.io/healthy-threshold-count: '3'
      alb.ingress.kubernetes.io/unhealthy-threshold-count: '3'
      alb.ingress.kubernetes.io/success-codes: '200-399'
      external-dns.alpha.kubernetes.io/hostname: {{ .Values.hostname }}
      kubernetes.io/ingress.class: alb
    generation: 1
    labels:
      app: {{ template "rancher.fullname" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
    name: rancher
    namespace: cattle-system
  spec:
    rules:
    - host: {{ .Values.hostname }}  # hostname to access rancher server
      http:
        paths:
        - backend:
            serviceName: rancher
            servicePort: 80
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
