apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/ssl-redirect: "false" # turn off ssl redirect for external.
    kubernetes.io/ingress.class: "nginx"
    generation: 1
    labels:
      app: {{ template "rancher.fullname" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
    name: rancher
    namespace: cattle-system
  spec:
    rules:
    - host: {{ .Values.hostname }}  # hostname to access rancher server
      http:
        paths:
        - backend:
            serviceName: rancher
            servicePort: 80
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
